# Generated by Django 3.0.4 on 2020-03-25 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('dob', models.DateField(blank=True, default=None, null=True)),
                ('mail', models.EmailField(blank=True, help_text='A valid email address, please.', max_length=254, null=True)),
                ('mobile_no', models.IntegerField(blank=True, default=None, null=True)),
                ('res_address', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('perm_address', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Userinfo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Details',
            },
        ),
        migrations.CreateModel(
            name='account_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsersAccountInfo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Accounts',
            },
        ),
    ]
