export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const PASSWORD_CHANGED = "PASSWORD_CHANGED";
export const PASSWORD_CHANGE_ERROR = "PASSWORD_CHANGE_ERROR";

export const GET_USERINFO = "GET_USERINFO";
export const ADD_USERINFO = "ADD_USERINFO";
export const EDIT_USERINFO = "EDIT_USERINFO";
export const DELETE_USERINFO = "DELETE_USERINFO";
export const GET_USERINFO_BY_ID = "GET_USERINFO_BY_ID";
